# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
version: 2
updates:
  - package-ecosystem: "npm" # Specify the package ecosystem, e.g., "npm", "pip", "maven", etc.
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly" # Frequency of updates, e.g., "daily", "weekly", "monthly"
    commit-message:
      prefix: "deps" # Optional: Customize the commit message prefix
    open-pull-requests-limit: 5 # Optional: Limit the number of open pull requests
    ignore:
      - dependency-name: "example-package" # Optional: Ignore specific dependencies
        versions: ["1.x", "2.x"] # Optional: Ignore specific versions
